== Epoker
En epok är en tidsperiod som präglas av ett tänkesätt.
En epok kan vara olika tidsperioder. Det finns inga speciella tidskrav.

* Förhistoriska tiden
* Högkulturerna
* Antiken 
* Medeltiden 
* Renässansen var en "pånyttfödelse" där man började blicka tillbaka på Antiken.
* Upplysningen var när man började tänka på ett naturvetenskapligt sätt.
* Romantiken var en reaktion på upplysningen, man tänkte mer på känslor.

== Prata om prov
Vi kommer få ett papper med frågor och ett papper med linjer. 
Vi skriver svaren på det linjerade pappret. 
Inget klotter, skriv så snyggt som möjligt.
Skriv så bra svenska som möjligt, hafsa inte bara ner det.

== Feodalism
_DET HÄR KOMMER INTE VARA PÅ PROVET_

När romarriket föll på 500-talet hade man det feudala systemet tills kungarna fick mer makt vid slutet av 1400-talet.
De nya kungarna i Europa hade till skillnad från Rom inte så mycket pengar och militärmakt.
Genom att skänka mark till hövdingar i utbyte mot soldater fick kungarna militärmakt.
Riddarna hade i uppgift att kriga medan bönderna fick i jobb att förse riddarna med förnödenheter.

Sammanfattat: *Kungen* gav *riddarna* mark, som försöjdes av *bönderna*.