== Vad avgör muskelstyrka?

Det beror på hur musklerna arbetar, på deras fysiologi, deras uppbyggnad.
 På sammarbetet mellan leder, nerver och muskler och teknik och mental förmåga.

Vid dynamisk muskelstyrka sker en rörelse i leden.
Vid statisk muskelstyrka är leden stilla.

Båda formerna kan vara maximala eller uthålliga.
Maximalt innebär att man gör övningen ett fåtal gånger under en kort period, medan uthålligt betyder att man gör övningen många gången under en längre period.

== Muskelstyra utifrån fysiologi

Det som främst avgör hur stark du är är musklernas uppbyggnad.
Musklerna består av muskelfibrer. Ju fler ock större muskelfibrerna är, desto större kraft.
Det betyder dock inte att musklerna är uthålliga.

För att en muskel ska komma igång krävs att den får signaler från nervsystemet.
Nervceller, nervtrådar och de muskelfibrer de har kontakt med kallas för en motorisk enhet.

Styrkan i en muskelkontraktion kan påverkas på två sätt: antingen kan frekvensen nervsignaler ökas, eller så kan antalet motoriska enheter vara högt.

Muskler som arbetar med precision har mindre fibrer per enhet än de muskler som endast arbetar med större kraft.

== Varför träna muskelstyrka?

Vid god muskelstyrka är det mindre risk att lida skador vid olyckor, till exempel fall.
Muskelstyrka kan även hjälpa vid belastningsskador på grund av stillasittande arbete och tunga lyft.

== Rörlighetsträning

Genom rörlighetsträning kan du öka din rörlighet.
Det är bindväven i musklerna som är aktuella vid rörlighetsträning.
Ju varmare bindväven är; desto mer flexibel är den. Därför är det viktigt att värma upp musklerna innan stretchning.

Vid dynamisk töjning rör man sig lite medan man stretchar.
Vid statisk töjning är man still när man stretchar.

== Vilka funktioner har benen?

Benens funktioner är följande:

* Att skydda
* Att stöda
* Utföra rörelser
* Lagra mineraler
* Bilda blodkroppar

Det finns olika typer av ben. Bland annat rörben, korta- platta- och oregelbundna ben och sesamben.

Rörbenet består av flera delar:

* Diafys (skaft)
* Epifys (ände)
* Metafys (brosk, tillväxtzon)
* Benhinna
* Ledbrosk

Korta ben saknar epifys och återfinns i till exempel händer och fötter.
Platta ben är platta. Finns i till exempel huvud och skuldra.
Oregelbundna ben har ingen speciell form. Till exempel ryggkotor.
Sesamben är ovala och sitter ofta i en muskelsena. Till exempel knäskålen.

Brosk är mellan ben och är mjukare än ben. Det skyddar mot slitage. Det finns i till exempel leder, näsa, öran.
Senor finns i änden av muskeln. De fäster muskeln i skelettet. Det är den svagaste delen av muskeln och oftast den som skadas.

== Leder och ligament

Leder är de ställen där två eller flera ben förenas.
Ligament håller ihop benen i en led. Tillsamman med muskler som korsar lederna skapar de stabilitet.

== Muskelvävnad

Glatt muskulatur finns i innre organ och blodkärl.
Hjärtmuskulatur finns enbart i hjärtat.
Skelettmuskulatur fäster i skelettet och ger rörelse i ben och leder.

Skelettmuskulaturens förmågor:

* Den kan sträckas ut
* Den kan återgå till normallängd
* Den kan förkortas (kontrahera)

Skelettmuskler är omslutna av bindväv som kallas Epimysium.
Innanför epimysium finns flera buntar muskelfibrer.
En muskelfiber består av flera myofibriller. De ger den sammandragande förmågan.
Myofibrillerna omges av Sarkolemma och varje myofibrill omges av sarkoplasma.
Myofibrillerna består av omväxlande mörka och ljusa filament av proteiner, Aktin och Myosin.

Aktin och myosin skapar muskelns rörelse. Myosinen klättrar fram och tillbaka längs aktinet.

Man kan ha olika typer av muskelfibrer: Snabba (ljusa) och långsamma (mörka).
Förhållandet beror på dels ärftlighet och dels på träning.

De snabba muskelfibrerna är stora och finns många av i muskler som används vid aktiviteter som kräver styrka.
Långsamma muskelfibrer är mindre och används vid aktiviteter som kräver uthållighet.
Till exempel har en sprinter många snabba fibrer, medan en långdistanslöpare har många långsamma fibrer.

== Blodkärl

Blodkärlens funktion är att tillföra blod till vävnader och ta tillbaka blod till hjärtat.

Artillärer transporterar blod till vävnader, kapillärer till celler och vener transporterar blodet tillbaka till hjärtat.